### ISSUE TITLE
Release without .tox directory?

### ISSUE THREAD

**Issue by wesm** [getpelican/feedgenerator#17]
I was digging into why the feedgenerator tarball is 4.1MB and see that there were some issues and PRs about this a few years ago but there has not been a release to PyPI since then. Any chance?

https://pypi.org/project/feedgenerator/#files

**Comment by justinmayer** [comment]
Hey Wes. Just to be clear, are you asking whether we can issue a release from master in its current form? Or do you think something else needs to be done first?

**Comment by avaris** [comment]
I think #12 fixed the issue and a new release would be fine.

**Comment by justinmayer** [comment]
I released [version 1.9.1](https://github.com/getpelican/feedgenerator/releases/tag/1.9.1), now available on [PyPI](https://pypi.org/project/feedgenerator/).

**Comment by wesm** [comment]
thanks!
