### ISSUE TITLE
feature_request(validation): Non-ASCII symbols in URI

### ISSUE THREAD

**Issue by Kristinita** [getpelican/feedgenerator#21]
### 1. Summary

If URI of my articles/pages contain Non-ASCII symbols, feedgenerator generate not valid feeds. Validation message:

```text
Sorry

This feed does not validate.

    line 16, column 61: id is not a valid TAG: tag:kristinita.netlify.app,2018-04-05:/Кира-Богиня.html [help]

                <id>tag:kristinita.netlify.app,2018-04-05:/Кира-Богиня.html</id>
```

![id is not valid tag](https://i.imgur.com/DroQG2M.png)

### 2. Possible solution

I think, it would be nice [**encode**](https://en.wikipedia.org/wiki/Percent-encoding) Non-ASCII symbols.

See W3C Feed Validation Service [**documentation**](https://validator.w3.org/feed/docs/error/InvalidTAG.html) for error I’m getting:

> Ensure that the URI: (…)
>
> Followed by any number of characters which are valid in a URI. Special characters may be escaped using [**percent encoding**](https://tools.ietf.org/html/rfc3986#section-2.1).

### 3. MCVE

Simply feed, generated by Pelican feedgenerator.

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>Kira Goddess</title>
    <link href="https://kristinita.netlify.app/" rel="alternate"/>
    <link href="https://kristinita.netlify.app/feeds/misc.atom.xml" rel="self"/>
    <id>https://kristinita.netlify.app/</id>
    <updated>2020-09-24T18:57:33+03:00</updated>
    <entry>
        <title>Kira Goddess</title>
        <link href="https://kristinita.netlify.app/kira-goddess.html" rel="alternate"/>
        <published>2020-09-24T18:57:33+03:00</published>
        <updated>2020-09-24T18:57:33+03:00</updated>
        <author>
            <name>Sasha Chernykh</name>
        </author>
        <id>tag:kristinita.netlify.app,2018-04-05:/Кира-Богиня.html</id>
        <content type="html">Kira Goddess!</content>
    </entry>
</feed>
```

In examples below I change content of bottom `<id>` tag

### 4. Steps to reproduce

I pasted my source to **<https://validator.w3.org/feed/#validate_by_input>** → `Validate`.

#### 5.1. Valid

1. All symbols are ASCII:

    ```xml
    <id>tag:kristinita.netlify.app,2018-04-05:/Kira-Goddess.html</id>
    ```

1. [**Percent-encoding**](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding) URN:

    ```xml
    <id>tag:kristinita.netlify.app,2018-04-05:/%D0%9A%D0%B8%D1%80%D0%B0-%D0%91%D0%BE%D0%B3%D0%B8%D0%BD%D1%8F.html</id>
    ```

#### 5.2. Not valid

1. Cyrillic symbols:

    ```xml
    <id>tag:kristinita.netlify.app,2018-04-05:/Кира-Богиня.html</id>
    ```

1. Any non-ASCII characters:

    ```xml
    <id>tag:kristinita.netlify.app,2018-04-05:/Kira-…-Goddess.html</id>
    ```

Thanks.

**Comment by venthur** [comment]
I assume this has been fixed some time ago, although I didn't bother to check. However I added a test case that cannot reproduce your problem anymore. I.e. If I add a non-ASCII character into a link, it will be properly encoded using percent-encoding in the ID of an Atom string.
