### ISSUE TITLE
which python versions do you want to support?

### ISSUE THREAD

**Issue by venthur** [getpelican/feedgenerator#26]
currently there's a mix of various seemingly supported python versions in the repo:
* `.github/workflows/main.yml`: tests against py37..py39
* `setup.py` claims: py27, py35..py38
* `tox.ini` claims: py26, py27, py32..py35

which versions do you want to support? i propose do drop python2 completely and remove make py36 the oldest supported version for now.

**Comment by justinmayer** [comment]
> which versions do you want to support?

The currently-supported Python versions: 3.6 – 3.9

> * `.github/workflows/main.yml`: tests against py37..py39

Looks to me like 3.6 through 3.9: https://github.com/getpelican/feedgenerator/blob/ae04e8a05b5136eebbc9343137a7e0987737bf50/.github/workflows/main.yml#L14

> * `setup.py` claims: py27, py35..py38
> * `tox.ini` claims: py26, py27, py32..py35

Fixed in 16c982f, so now all the supported Python versions should be consistent.

**Comment by venthur** [comment]
Ok, then brace yourself for a giant py2 removal PR.

**Comment by justinmayer** [comment]
Sounds great. It will also be a good opportunity to add and run `pre-commit run --all-files --py36-plus`. 👍
