### ISSUE TITLE
no  "updated" tags generated by feedgenerator 1.8

### ISSUE THREAD

**Issue by vioan** [getpelican/feedgenerator#8]
It seems that if _feedgenerator 1.8_ is used, there is no "updated" tag for each entry in atom feed. And because of this the feed is pushing always a lot of old posts to the reader. I tried pelican 3.6.3 and 3.6.4dev and it seems that both of them are pulling the 1.8 version of feedgenerator. The solution was to install first _feedgenerator 1.6_ and then install pelican.

**Comment by justinmayer** [comment]
@vioan: See #7

**Comment by vioan** [comment]
@justinmayer great, perhaps this will speed up the review and merging :)

**Comment by justinmayer** [comment]
Addressed via above-mentioned pull request, which has been merged.

**Comment by ingwinlu** [comment]
@justinmayer really needs a pypi release, else pelican pulls in 1.8 which is broken

**Comment by justinmayer** [comment]
@ingwinlu: Version 1.9 has been published to PyPI. Many thanks for prodding me.
